package types;

public enum Direction {
	NORTH, NORTHEAST, EAST, SOUTHEAST, SOUTH, SOUTHWEST, WEST, NORTHWEST, AWAYNORTH, AWAYNORTHEAST, AWAYEAST, AWAYSOUTHEAST, AWAYSOUTH, AWAYSOUTHWEST, AWAYWEST, AWAYNORTHWEST, NOWHERE
}
